services:
  - type: web
    name: ncaaf-frontend
    env: python
    buildCommand: |
      git submodule update --init --recursive || true
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATA_DIR
        value: /opt/render/project/src/data
    plan: free
    autoDeploy: true
